RaceMaker/RaceMaker/Models/CreateRace.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RaceMaker.Models
{
    public class CreateRace
    {
        [Key]
        public int ID { get; set; }

        [Required]
        [Display(Name = "Race Name")]
        public string RaceName { get; set; }

        [Required]
        [Display(Name = "Race Location")]
        public string RaceLocation { get; set; }

        [Required]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        [Display(Name = "Race Date")]
        public DateTime RaceDate { get; set; }

        [Required]
        [Display(Name = "Race Distance")]
        public int RaceDistance { get; set; }

        [Required]
        [Display(Name = "Race Fee")]
        public double RaceCost { get; set; }

        [Display(Name = "Race Description")]
        public string RaceDescription { get; set; }
        [Required]
        [Display(Name = "Race Administrator Email")]
        public string AdminEmail { get; set; }

        [Display(Name = "Race Administrator Password")]
        public string AdminPassword { get; set; }
        public string FilePath { get; set; }
        public string FileName { get; set; }
        [Display(Name = "Additional Information")]
        public string AdditionalInformation { get; set; }
        public string ImagePath { get; set; }
        public string ImageName { get; set; }
        public double CenterLat { get; set; }
        public double CenterLong { get; set; }
        public double CourseLat { get; set; }
        public double CourseLng { get; set; }
        public double OriginLat { get; set; }
        public double OriginLng { get; set; }
        public double DestinationLat { get; set; }
        public double DestinationLng { get; set; }

        [ForeignKey("CreateRaceID")]
        public virtual ICollection<RaceSignUp> RaceSignUps { get; set; } = new HashSet<RaceSignUp>();

        public List<RaceCoursePoint> RaceCoursePoints { get; set; }
        public List<string> waypoints { get; set; }

        //[ForeignKey("RacePointNumber")]
        /*public virtual ICollection<RaceCoursePoint> RaceCoursePoint { get; set; }*/ //= new HashSet<RaceCoursePoint>();

        

    }
}

RaceMaker/RaceMaker/Controllers/CreateRacesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using RaceMaker.Models;
using System.IO;
using RestSharp;
using MailKit;
using MailKit.Net.Smtp;
using MimeKit;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Configuration;
using System.Xml;
using System.Text;
using System.Data.SqlClient;
using OfficeOpenXml;

namespace RaceMaker.Models
{
    public class CreateRacesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        

        // GET: CreateRaces
        public ActionResult Index(int? id)
        {
            return View(db.CreateRaces.ToList()); //shows all races  
        }

        // GET: CreateRaces/Details/5
        public ActionResult Details(int? id)
      {//find all race points with the same Primary Key after creating JunctionTable
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CreateRace createRace = db.CreateRaces.Find(id);
            var raceDataPoints = db.RaceCoursePoints.Where(x => x.CreateRace.ID == id).OrderBy(a => a.PointNumber).ToList();
            createRace.RaceCoursePoints = raceDataPoints;
            if (createRace == null)
            {
                return HttpNotFound();
            }
            return View(createRace);
        }

        public ActionResult RunnerDetails(int? id)
      {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CreateRace createRace = db.CreateRaces.Find(id);

            var raceDataPoints = db.RaceCoursePoints.Where(x => x.CreateRace.ID == id).OrderBy(a => a.PointNumber).ToList();
            createRace.RaceCoursePoints = raceDataPoints; 

            if (createRace == null)
            {
                return HttpNotFound();
            }
            return View(createRace);
        }

        // GET: CreateRaces/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CreateRaces/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,RaceName,RaceLocation,RaceDate,RaceDistance,RaceCost,RaceDescription,AdminEmail,AdminPassword")] CreateRace createRace)
        {
            if (ModelState.IsValid)
            {
                createRace.RaceSignUps = new List<RaceSignUp>();

                db.CreateRaces.Add(createRace);
                db.SaveChanges();
                return RedirectToAction("Details", new { id = createRace.ID });
            }
            return View(createRace);
        }

        // GET: CreateRaces/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CreateRace createRace = db.CreateRaces.Find(id);
            if (createRace == null)
            {
                return HttpNotFound();
            }
            return View(createRace);
        }

        // POST: CreateRaces/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,RaceName,RaceLocation,RaceDate,RaceDistance,RaceCost,FilePath,FileName,AdditionalInformation")] CreateRace createRace)
        {
            if (ModelState.IsValid)
            {
                db.Entry(createRace).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", new { id = createRace.ID });
            }
            return View(createRace);
        }

        // GET: CreateRaces/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CreateRace createRace = db.CreateRaces.Find(id);
            if (createRace == null)
            {
                return HttpNotFound();
            }
            return View(createRace);
        }

        // POST: CreateRaces/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CreateRace createRace = db.CreateRaces.Find(id);
            db.CreateRaces.Remove(createRace);
            db.SaveChanges();
            return RedirectToAction("ShowMyRaces");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult ShowMyRaces(int? id)
        {
            //this logic needs to be somewhere exclusively for RaceCreators
            string userId = User.Identity.GetUserId();
            ApplicationUser currentUser = db.Users.FirstOrDefault(x => x.Id == userId);

            //CreateRace race = db.CreateRaces.Find(id);
            //CreateRace race;
            if (currentUser.Email != null)
            {

                var races = db.CreateRaces.Where(s => s.AdminEmail == currentUser.Email);
                races.ToList();
                if(races == null)
                {
                    return HttpNotFound();
                }
                else
                {
                    return View(races);
                }
                
            }
            else
            {
                return View(db.CreateRaces.ToList()); //shows all races 
            }
        }

        public ActionResult RedirectToSignUp()
        {
            RaceSignUp raceSignUp = new RaceSignUp();
            return View("../RaceSignUps/Create", raceSignUp);
        }

        //public ActionResult Upload(HttpPostedFileBase file)
        //{
        //    string path = Server.MapPath("~/Files/" + file.FileName);
        //    file.SaveAs(path);
        //    ViewBag.path = path;
        //    return View();
        //}

        [HttpGet]
        public ActionResult UploadFile(int? id)
            {
            CreateRace createRace = db.CreateRaces.Find(id);
            //query table to find correct race based on ID
            //pass in race object to view 
            return View(createRace);
            }
        [HttpPost]
        public ActionResult UploadFile(HttpPostedFileBase file, int? id)
        {
            CreateRace createRace = db.CreateRaces.Find(id);
            try
            {
                if (file.ContentLength > 0)
                {
                    
                    string _FileName = Path.GetFileName(file.FileName);
                    string _path = Path.Combine(Server.MapPath("~/Files"), _FileName);
                    createRace.FileName = _FileName;
                    createRace.FilePath = _path;
                    db.SaveChanges();
                    file.SaveAs(_path);
                }
                ViewBag.Message = "File Uploaded Successfully!!";

                return View(createRace);
            }
            catch
            {
                ViewBag.Message = "File upload failed!!";
                return View();
            }
        }

        [HttpGet]
        public ActionResult UploadImage(int? id)
        {
            CreateRace createRace = db.CreateRaces.Find(id);
            //query table to find correct race based on ID
            //pass in race object to view 
            return View(createRace);
        }
        [HttpPost]
        public ActionResult UploadImage(HttpPostedFileBase file, int? id)
        {
            CreateRace createRace = db.CreateRaces.Find(id);
            try
            {
                if (file.ContentLength > 0)
                {

                    string _FileName = Path.GetFileName(file.FileName);
                    string _path = Path.Combine(Server.MapPath("~/Images"), _FileName);
                    createRace.ImageName = _FileName;
                    createRace.ImagePath = _path;
                    db.SaveChanges();
                    file.SaveAs(_path);
                }
                ViewBag.Message = "Image Uploaded Successfully!!";

                return View(createRace);
            }
            catch
            {
                ViewBag.Message = "Image upload failed!!";
                return View();
            }
        }

        public ActionResult Download()
        {
            string path = Server.MapPath("~/Files/");
            DirectoryInfo dirInfo = new DirectoryInfo(path);
            FileInfo[] files = dirInfo.GetFiles("*.*");

            return View(files);
        }


        public ActionResult DisplayEntries(int? id)
        {
            CreateRace createRace = db.CreateRaces.Find(id);
            var entries = db.RaceSignUps.Where(s => s.RaceID == createRace.ID).ToList();
            return View(entries);
        }

        [HttpGet]
        public ActionResult SendEmail(int? id)
        {
            //CreateRace createRace = db.CreateRaces.Find(id);
            //query table to find correct race based on ID
            //pass in race object to view 
            return View();
        }
        [HttpPost]
        public ActionResult SendEmail()
        {//possibly create binds
            //CreateRace createRace = db.CreateRaces.Find(id);
            try
            {
                // Compose a message

RaceMaker/RaceMaker/Views/CreateRaces/Create.cshtml
@model RaceMaker.Models.CreateRace

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Create A Race</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.AdminEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AdminEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AdminEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.AdminPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AdminPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AdminPassword, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.RaceName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RaceName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RaceName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RaceLocation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RaceLocation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RaceLocation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RaceDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RaceDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RaceDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RaceDistance, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RaceDistance, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RaceDistance, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RaceCost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RaceCost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RaceCost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RaceDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RaceDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RaceDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AdditionalInformation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.AdditionalInformation, @*new { htmlAttributes =*@ new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AdditionalInformation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create Race" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@*@using (Html.BeginForm("Upload", "Upload", FormMethod.Post, new { enctype = "multipart/form-data" }))
{   
    <input type="file", name="file", id="file"/>
    @*<input type="submit" value="Upload" />
}*@

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RaceMaker/RaceMaker/Views/CreateRaces/Delete.cshtml
@model RaceMaker.Models.CreateRace

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CreateRace</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RaceName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RaceName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RaceLocation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RaceLocation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RaceDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RaceDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RaceDistance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RaceDistance)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RaceCost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RaceCost)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

RaceMaker/RaceMaker/Views/CreateRaces/DisplayEntries.cshtml
@model IEnumerable<RaceMaker.Models.RaceSignUp>

@{
    ViewBag.Title = "DisplayEntries";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Race Entries</h2>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gender)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TshirtSize)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateOfBirth)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TshirtSize)
            </td>
        </tr>
    }
</table>

RaceMaker/RaceMaker/Views/CreateRaces/Edit.cshtml
@model RaceMaker.Models.CreateRace

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CreateRace</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.RaceName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RaceName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RaceName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RaceLocation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RaceLocation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RaceLocation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RaceDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RaceDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RaceDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RaceDistance, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RaceDistance, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RaceDistance, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RaceCost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RaceCost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RaceCost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RaceMaker/RaceMaker/Views/CreateRaces/ExportDataFromDatabase.cshtml
@{
    ViewBag.Title = "ExportDataFromDatabase";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Export Data From Database</h2>

RaceMaker/RaceMaker/Views/CreateRaces/Index.cshtml
@model IEnumerable<RaceMaker.Models.CreateRace>


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>My Races</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.RaceName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RaceLocation)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RaceDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RaceDistance)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RaceCost)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.RaceName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RaceLocation)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RaceDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RaceDistance)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RaceCost)
        </td>
        <td>
           
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID }) |


            @Html.ActionLink("Sign Up", "Create", "RaceSignUps", new { RaceID =item.ID}, null)
        </td>
    </tr>
}

</table>

RaceMaker/RaceMaker/Views/CreateRaces/SendEmail.cshtml
@{
    ViewBag.Title = "SendEmail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Send Email</h2>

@using (Html.BeginForm())
{

    <div>
        @*@Html.TextBox("file", "", new { type = "file" }) <br />*@

        <input type="submit" value="Send Email Blast" />

        @ViewBag.Message

    </div>
}
<p>

</p>

@Html.ActionLink("Back to List", "Index") 
@*@Html.ActionLink("Back to Race Details", "Details", new { id = Model.ID })*@

RaceMaker/RaceMaker/Views/CreateRaces/ShowMyRaces.cshtml
@model IEnumerable<RaceMaker.Models.CreateRace>
@{
    ViewBag.Title = "ShowMyRaces";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div align="center"><h2>My Races</h2></div>


<p align="center">
    @Html.ActionLink("Create A New Event", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.RaceName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RaceLocation)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RaceDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RaceDistance)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RaceCost)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.RaceName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RaceLocation)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RaceDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RaceDistance) miles
            </td>
            <td>
                $@Html.DisplayFor(modelItem => item.RaceCost)
            </td>
            <td>

                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ID }) |
                @Html.ActionLink("Send Email", "SendEmail", "CreateRaces", new { id = item.ID } )
                @*@Html.ActionLink("Sign Up", "User", "SignUpForRace", new { id = item.ID })*@
            </td>
        </tr>
    }

</table>

RaceMaker/RaceMaker/Views/CreateRaces/UploadFile.cshtml
@model RaceMaker.Models.CreateRace
@{
    ViewBag.Title = "UploadFile";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container-fluid body-content" align='center'>
    <div style="padding-bottom: 10px">
        <h2>Upload File</h2>
    </div>
    </div>
<div class="container-fluid body-content" float='left'>
    @using (Html.BeginForm("UploadFile", "CreateRaces", "UploadFile", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {

        <div style="padding-bottom: 10px">
            @Html.TextBox("file", "", new { type = "file" }) <br />

            <input type="submit" value="Upload" />

            @ViewBag.Message
        </div>

        <div class="container-fluid body-content" align='center'>

            <img src="~/Images/runnerStart.jpg" alt="RaceImage" />

        </div>
    }
</div>

    <p>

    </p>
<div class="container-fluid body-content" align='center'>
    @Html.ActionLink("Back to List", "Index") |
    @Html.ActionLink("Back to Race Details", "Details", new { id = Model.ID })
</div>

RaceMaker/RaceMaker/Views/CreateRaces/UploadImage.cshtml
@model RaceMaker.Models.CreateRace
@{
    ViewBag.Title = "UploadFile";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid body-content" align='center'>
    <h2>Upload Image</h2>

    @using (Html.BeginForm("UploadImage", "CreateRaces", "UploadFile", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {

        <div>
            @Html.TextBox("file", "", new { type = "file" }) <br />

            <input type="submit" value="Upload" />

            

        </div>
    }
    </div>
    <p>

    </p>
    <div class="container-fluid body-content" align='center'>
        <img src="~/Images/@Model.ImageName" />
    </div>


    @*<div class="jumbotron" align="right" , style="background-image: url(../Images/runnerGraphic.jpg)">*@

    <div class="container-fluid body-content" align='center'>
        @Html.ActionLink("Back to List", "Index") |
        @Html.ActionLink("Back to Race Details", "Details", new { id = Model.ID })
    </div>