RaceMaker/RaceMaker/Models/RaceSignUp.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations.Schema;

namespace RaceMaker.Models
{
    public class RaceSignUp
    {
        [Key]
        public int ID { get; set; }

        [Required]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Required]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Required]
        [Display(Name = "Gender")]
        public string Gender { get; set; }

        [Required]
        [Display(Name = "Date Of Birth")]
        public DateTime DateOfBirth { get; set; }

        [Required]
        [Display(Name = "T-Shirt Size")]
        public string TshirtSize { get; set; }

        [Required]
        [Display(Name = "Participant Email")]
        public string Email { get; set; }

        public int RaceID { get; set; }


        [ForeignKey("RaceSignUpID")]
        public virtual ICollection<CreateRace> CreateRaces { get; set; } = new HashSet<CreateRace>();




    }
}

RaceMaker/RaceMaker/Controllers/RaceSignUpsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RaceMaker.Models;
using System.Configuration;
using Stripe;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity;
using System.IO;
using MimeKit;
using MailKit.Net.Smtp;

namespace RaceMaker.Controllers
{
    public class RaceSignUpsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index()
        {
            return View(db.CreateRaces.ToList());
        }

        // GET: RaceSignUps
        public ActionResult PaymentConfirmation()
        {
            var stripePublishKey = ConfigurationManager.AppSettings["pk_test_Hoa0Coqp2Ao1v3i1wYoo494m"];
            ViewBag.StripePublishKey = "pk_test_Hoa0Coqp2Ao1v3i1wYoo494m";
            return View();
            //return View(db.RaceSignUps.ToList()); uncomment this part after testing the Stripe API
            //var races = from r in db.CreateRaces
            //            orderby r.RaceDate ascending
            //            select r;
            //return View(races);
            

            //where for only race director races

        }

        // GET: RaceSignUps/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RaceSignUp raceSignUp = db.RaceSignUps.Find(id);
            if (raceSignUp == null)
            {
                return HttpNotFound();
            }
            return View(raceSignUp);
        }

        // GET: RaceSignUps/Create
        public ActionResult Create(int? id)
        {
            return View();
        }

        // POST: RaceSignUps/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,FirstName,LastName,Gender,DateOfBirth,TshirtSize,RaceID,Email")] RaceSignUp raceSignUp, int? id)
        {///need to add an empty list for CreateRaces so it isnt null
            if (ModelState.IsValid)
            {

                raceSignUp.CreateRaces = new List<CreateRace>();

                var races = db.RaceSignUps.Where(c => c.ID == raceSignUp.ID).Select(p => p.CreateRaces);
                races.ToList();

                CreateRace cr = db.CreateRaces.Where(c => c.ID == id).FirstOrDefault();

                raceSignUp.CreateRaces.Add(cr); 

                db.RaceSignUps.Add(raceSignUp);

                db.SaveChanges();
                return RedirectToAction("PaymentConfirmation");
            }

            return View(raceSignUp);
        }

        // GET: RaceSignUps/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RaceSignUp raceSignUp = db.RaceSignUps.Find(id);
            if (raceSignUp == null)
            {
                return HttpNotFound();
            }
            return View(raceSignUp);
        }

        // POST: RaceSignUps/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID")] RaceSignUp raceSignUp)
        {
            if (ModelState.IsValid)
            {
                db.Entry(raceSignUp).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(raceSignUp);
        }

        // GET: RaceSignUps/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RaceSignUp raceSignUp = db.RaceSignUps.Find(id);
            if (raceSignUp == null)
            {
                return HttpNotFound();
            }
            return View(raceSignUp);
        }

        // POST: RaceSignUps/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            RaceSignUp raceSignUp = db.RaceSignUps.Find(id);
            db.RaceSignUps.Remove(raceSignUp);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult OrderByDate()
        {
            var races = from r in db.CreateRaces
                        orderby r.RaceDate ascending
                        select r;
            return View(races);
        }

        //public ActionResult SignUpForRace(int? id)
        //{

        //}

        public ActionResult OrderByDay()
        {
            var races = (from c in db.CreateRaces
                    .OrderByDescending(c => c.RaceDate)
                         select c);
            return View(races.ToList());
        }

        public ActionResult Charge(string stripeEmail, string stripeToken)
        {
            var customers = new StripeCustomerService();
            var charges = new StripeChargeService();

            var customer = customers.Create(new StripeCustomerCreateOptions
            {
                Email = stripeEmail,
                SourceToken = stripeToken
            });

            var charge = charges.Create(new StripeChargeCreateOptions
            {
                Amount = 1300,//charge in cents
                Description = "Sample Charge",
                Currency = "usd",
                CustomerId = customer.Id
            });

            // further application specific code goes here

            return View();
        }

        public ActionResult ConfirmRegistration()
        {
            return View();
        }

        public ActionResult ShowMyRacesRunning(int? id)
        {
            {
                //this logic needs to be somewhere exclusively for RaceCreators
                string userId = User.Identity.GetUserId();
                ApplicationUser currentUser = db.Users.FirstOrDefault(x => x.Id == userId);

                //CreateRace race = db.CreateRaces.Find(id);
                //CreateRace race;
                if (currentUser.Email != null)
                {
                    var races = db.CreateRaces.Where(s => s.RaceSignUps.Any(c => c.Email == currentUser.Email));
                    //get ID from those races, then display race info
                    //select all RaceID's 
                    //need a list of entries
                    races.ToList();
                    if (races == null)
                    {
                        return HttpNotFound();
                    }
                    else
                    {
                        return View(races);
                    }

                }
                else
                {
                    return View(db.CreateRaces.ToList()); //shows all races 
                }
            }
        }

        [HttpGet]
        public ActionResult UploadCSV(int? id)
        {
            CreateRace createRace = db.CreateRaces.Find(id);
            //query table to find correct race based on ID
            //pass in race object to view 
            return View();
        }

        [HttpPost]
        public ActionResult UploadCSV(HttpPostedFileBase file, int id)
        {

            // Verify that the user selected a file
            if (file != null && file.ContentLength > 0)
            {

                System.IO.StreamReader csvReader = new StreamReader(file.InputStream);
                {
                    string inputLine = "";
                    while ((inputLine = csvReader.ReadLine()) != null)
                    {
                        string[] values = inputLine.Split(new Char[] { ',' });
                        RaceSignUp raceSignUp = new RaceSignUp();
                        raceSignUp.FirstName = values[0];
                        raceSignUp.LastName = values[1];
                        raceSignUp.Gender = values[2]; 
                        raceSignUp.DateOfBirth = DateTime.Parse(values[3]);
                        raceSignUp.TshirtSize = values[4];
                        raceSignUp.Email = values[5];
                        raceSignUp.RaceID = id;

                        CreateRace cr = db.CreateRaces.Where(c => c.ID == id).FirstOrDefault();
                        raceSignUp.CreateRaces.Add(cr);

                        //CreateRace cr = new CreateRace();
                        ////need to add hashset value for this given race
                        //raceSignUp.CreateRaces = values[cr];
                        db.RaceSignUps.Add(raceSignUp);
                        db.SaveChanges();
                    }
                    csvReader.Close();
                }
            }
            // redirect back to the index action to show the form once again
            return RedirectToAction("Index");
        }

        public ActionResult Search(string searchBy, string search)
        {
            if (searchBy == "RaceName")
                return View(db.CreateRaces.Where(x => x.RaceName.StartsWith(search) || search == null).ToList());
            else if (searchBy == "RaceLocation")
                return View(db.CreateRaces.Where(x => x.RaceLocation.StartsWith(search) || search == null).ToList());

RaceMaker/RaceMaker/Controllers/SendEmailWithAttachmentsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using RaceMaker.Models;

namespace RaceMaker.Controllers
{
    public class SendEmailWithAttachmentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: /SendMailer/
        //[HttpGet]
        public ActionResult Index(int? id)
        {
            return View();
        }

        /// <summary>

        /// Send Mail with Gmail

        /// </summary>

        /// <param name="objModelMail">MailModel Object, keeps all properties</param>

        /// <param name="fileUploader">Selected file data, example-filename,content,content type(file type- .txt,.png etc.),length etc.</param>

        /// <returns></returns>

        [HttpPost]

        public ActionResult Index(RaceMaker.Models.SendEmailWithAttachment objModelMail, HttpPostedFileBase fileUploader)

        {

            if (ModelState.IsValid)

            {
                string from = "raceMaker12@gmail.com"; //example:- sourabh9303@gmail.com

                using (MailMessage mail = new MailMessage(from, objModelMail.To))

                {

                    mail.Subject = objModelMail.Subject;

                    mail.Body = objModelMail.Body;

                    if (fileUploader != null)

                    {

                        string fileName = Path.GetFileName(fileUploader.FileName);

                        mail.Attachments.Add(new Attachment(fileUploader.InputStream, fileName));

                    }

                    mail.IsBodyHtml = false;

                    SmtpClient smtp = new SmtpClient();

                    smtp.Host = "smtp.gmail.com";

                    smtp.EnableSsl = true;

                    NetworkCredential networkCredential = new NetworkCredential(from, "Running2win");

                    smtp.UseDefaultCredentials = true;

                    smtp.Credentials = networkCredential;

                    smtp.Port = 587;

                    smtp.Send(mail);

                    ViewBag.Message = "Sent";

                    return View("Index", objModelMail);

                }

            }

            else

            {

                return View();

            }

        }

    }

}

RaceMaker/RaceMaker/Views/RaceSignUps/Charge.cshtml
@model RaceMaker.Models.CreateRace
@{
    ViewBag.Title = "Charge";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Your payment has successfully gone through!</h2>

@*@Html.ActionLink("Race Details", "Details", new { id = Model.ID }, null)*@

RaceMaker/RaceMaker/Views/RaceSignUps/ConfirmRegistration.cshtml
@model RaceMaker.Models.RaceSignUp

@{
    ViewBag.Title = "View";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Confirm Registration</h2>

                <table class="table">
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.FirstName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.LastName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Gender)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.DateOfBirth)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.TshirtSize)
                        </th>
                    </tr>
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => Model.FirstName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => Model.LastName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => Model.Gender)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => Model.DateOfBirth)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => Model.TshirtSize)
                        </td>
                    </tr>
                    </table>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Save" class="btn btn-default" />
                        </div>
                    </div>
</div>


<div>
    @Html.ActionLink("Back to List", "Index")
</div>

RaceMaker/RaceMaker/Views/RaceSignUps/Create.cshtml
@model RaceMaker.Models.RaceSignUp

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container-fluid body-content" align='center'>
    <h2>Register For A Race</h2>
    </div>
<div class="container-fluid body-content">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">

                @*<h4>Sign Up Now</h4>*@
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.DateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.TshirtSize, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.TshirtSize, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TshirtSize, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Register" class="btn btn-default" />
                    </div>
                </div>
            </div>

        }
    </div>


    <div class="container-fluid body-content" align='center'>
    @Html.ActionLink("Back to List", "Index")
</div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

RaceMaker/RaceMaker/Views/RaceSignUps/Delete.cshtml
@model RaceMaker.Models.RaceSignUp

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>RaceSignUp</h4>
    <hr />
    <dl class="dl-horizontal">
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

RaceMaker/RaceMaker/Views/RaceSignUps/Edit.cshtml
@model RaceMaker.Models.RaceSignUp

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>RaceSignUp</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RaceMaker/RaceMaker/Views/RaceSignUps/Email.cshtml
@{
    ViewBag.Title = "Email";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Email</h2>

<p>Email was succesfully sent!</p>

RaceMaker/RaceMaker/Views/RaceSignUps/Index.cshtml
@model IEnumerable<RaceMaker.Models.CreateRace>


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid body-content" align='center'>
    <h2>Upcoming Events</h2>

    <p>
        @*@Html.ActionLink("Create New", "Create")*@
        @using (Html.BeginForm("Search", "RaceSignUps", FormMethod.Get))
        //View then Controller
        {
            @Html.TextBox("search") <input type="submit" value="Search" />
            <b>Search By:</b>
            @Html.RadioButton("searchBy", "RaceName", true) <text>Race Name</text>
            @Html.RadioButton("searchBy", "RaceLocation") <text>Race Location</text>
            @Html.RadioButton("searchBy", "RaceDate") <text>Race Date</text>
            @Html.RadioButton("searchBy", "RaceDistance") <text>Race Distance</text>
            @Html.RadioButton("searchBy", "RaceCost") <text>Race Fee</text>
        }
    </p>
    @*<form asp-controller="RaceSignUps" asp-action="Index">
            <p>
                Race Name: <input type="text" name="SearchString">
                <input type="submit" value="Filter" />
            </p>
        </form>*@

    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.RaceName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RaceLocation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RaceDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RaceDistance)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RaceCost)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.RaceName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RaceLocation)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RaceDate)
                    @*@item.startDate.Value.ToShortDateString()*@
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RaceDistance) miles
                </td>
                <td>
                    $@Html.DisplayFor(modelItem => item.RaceCost)
                </td>
                <td>

                    @*@Html.ActionLink("Edit", "Edit", new { id=item.ID }) |*@
                    @Html.ActionLink("Details", "RunnerDetails", "CreateRaces", new { id = item.ID }, null) |
                    @*@Html.ActionLink("Delete", "Delete", new { id=item.ID }) |*@
                    @Html.ActionLink("Sign Up", "Create", "RaceSignUps", new { id = item.ID }, null) |
                    @Html.ActionLink("Upload CSV", "UploadCSV", "RaceSignUps", new { id = item.ID }, null)
                </td>
            </tr>
        }

    </table>
</div>

RaceMaker/RaceMaker/Views/RaceSignUps/OrderByDate.cshtml
@model RaceMaker.Models.RaceSignUp

@{
    ViewBag.Title = "OrderByDate";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>OrderByDate</h2>

<div>
    <h4>RaceSignUp</h4>
    <hr />
    <dl class="dl-horizontal">
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

RaceMaker/RaceMaker/Views/RaceSignUps/Search.cshtml
@model IEnumerable<RaceMaker.Models.CreateRace>


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid body-content" align='center'>
    <h2>Upcoming Events</h2>

    <p>
        @*@Html.ActionLink("Create New", "Create")*@
        @using (Html.BeginForm("Search", "RaceSignUps", FormMethod.Get))
        //View then Controller
        {
            @Html.TextBox("search") <input type="submit" value="Search" />
            <b>Search By:</b>
            @Html.RadioButton("searchBy", "RaceName", true) <text>Race Name</text>
            @Html.RadioButton("searchBy", "RaceLocation") <text>Race Location</text>
            @Html.RadioButton("searchBy", "RaceDate") <text>Race Date</text>
            @Html.RadioButton("searchBy", "RaceDistance") <text>Race Distance</text>
            @Html.RadioButton("searchBy", "RaceCost") <text>Race Fee</text>

            
            
        }
    </p>
    @*<form asp-controller="RaceSignUps" asp-action="Index">
            <p>
                Race Name: <input type="text" name="SearchString">
                <input type="submit" value="Filter" />
            </p>
        </form>*@

    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.RaceName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RaceLocation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RaceDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RaceDistance)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RaceCost)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.RaceName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RaceLocation)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RaceDate)
                    @*@item.startDate.Value.ToShortDateString()*@
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RaceDistance) miles
                </td>
                <td>
                    $@Html.DisplayFor(modelItem => item.RaceCost)
                </td>
                <td>

                    @*@Html.ActionLink("Edit", "Edit", new { id=item.ID }) |*@
                    @Html.ActionLink("Details", "RunnerDetails", "CreateRaces", new { id = item.ID }, null) |
                    @*@Html.ActionLink("Delete", "Delete", new { id=item.ID }) |*@
                    @Html.ActionLink("Sign Up", "Create", "RaceSignUps", new { id = item.ID }, null) |
                    @Html.ActionLink("Upload CSV", "UploadCSV", "RaceSignUps", new { id = item.ID }, null)
                </td>
            </tr>
        }

    </table>
</div>

RaceMaker/RaceMaker/Views/RaceSignUps/ShowMyRacesRunning.cshtml
@model IEnumerable<RaceMaker.Models.CreateRace>

@{
    ViewBag.Title = "My Upcoming Races";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div align="center"><h2>My Upcoming Races</h2></div>

<div>
    <hr />
    <dl class="dl-horizontal">
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.RaceName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.RaceLocation)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.RaceDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.RaceDistance)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.RaceCost)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.RaceName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.RaceLocation)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.RaceDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.RaceDistance) miles
                    </td>
                    <td>
                        $@Html.DisplayFor(modelItem => item.RaceCost)
                    </td>
                    <td>

                        @*@Html.ActionLink("Edit", "Edit", new { id = item.ID }) |*@
                        @Html.ActionLink("Details", "RunnerDetails", "CreateRaces", new { id = item.ID }, null) |
                        @*@Html.ActionLink("Delete", "Delete", new { id = item.ID }) |*@
                        @Html.ActionLink("Email Race Director", "Index", "SendEmailWithAttachments", new { id = item.ID }, null)
                        @*@Html.ActionLink("Sign Up", "User", "SignUpForRace", new { id = item.ID })*@
                    </td>
                </tr>
            }

        </table>

RaceMaker/RaceMaker/Views/RaceSignUps/UploadCSV.cshtml
@model RaceMaker.Models.RaceSignUp

@{
    ViewBag.Title = "UploadFile";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container-fluid body-content" align='center'>
    <h2>Upload CSV Entries</h2>
</div>
<div class="container-fluid body-content" align='center'>
   
        @using (Html.BeginForm("UploadCSV", "RaceSignUps", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div style="padding-bottom: 10px">
                <input type="file" name="File" id="File" />
                </div>
                <div style="padding-bottom: 10px">
                    <input type="submit" name="Submit" value="Upload" />
                    </div>
                    <span>@ViewBag.Message</span>
                    }
                </div>
<div class="container-fluid body-content" align='right'>
    
        <img src="~/Images/runnerStart.jpg" alt="RaceImage" />
    
</div>


    @*{

            <div>
                @Html.TextBox("CSV", "", new { type = "file" }) <br />


                    <input type="submit" value="Upload" />

                    @ViewBag.Message

                </div>
        }
        <p>

        </p>

        Html.ActionLink("Back to List", "Index") |
            @Html.ActionLink("Back to Race Details", "Details", new { id = Model.ID })*@